import type { APIRoute } from 'astro';


export const GET: APIRoute = ({ params, request }) => {

    const id = params.id!
    return new Response(
        JSON.stringify({
            success: true,
            description: allCodes[id]
        })
    )
}

export function getStaticPaths() {
    return Object.keys(allCodes).map((id: string) => {
        return {
            params: { id }
        }
    })
}

export const allCodes: any = {
    "acoustic_absorption": "\u003cp\u003eA lack of Acoustic Absorption can produce an unpleasant experience in\ndwellings. It can affect the clarity of the audio thus making it difficult to hold conversations.\u003c/p\u003e\n",
    "acoustic_insulation": "\u003cp\u003eNot all walls, windows or doors are equally effective at\nstopping the noise. People know this and therefore it becomes\na relevant input to their assessment of a space.\u003c/p\u003e\n\u003cp\u003eAcoustic insulation is not only expected to stop outside noises,\nbut also noise transferred between spaces.\u003c/p\u003e\n",
    "acoustic_privacy": "\u003cp\u003ePrivacy is the perception of being invaded by other people. Specifically for this model, it relates to\nother people hearing our actions.\u003c/p\u003e\n\u003cp\u003eThis is different from the perception of\n\u003ca href=\"code=bothering_others\"\u003ebothering others\u003c/a\u003e\nbecause privacy is not about \u003cem\u003eothers\u003c/em\u003e being\naffected, but ourselves.\u003c/p\u003e\n\u003cp\u003eThe \u003ca href=\"code=loss_of_visual_privacy\"\u003eloss of privacy\u003c/a\u003e associated with Daylight and Coolness is the\nsame concept. However, that case relates to the perception of being observed (e.g. through openings and windows).\u003c/p\u003e\n",
    "aesthetics": "\u003cp\u003eSome systems, materials, appliances, and design choices can be beneficial for the performance of the house while not being aesthetically attractive. This Trade-off, then, makes people choose between having a more comfortable but less beautiful home or having a more beautiful and less comfortable one.\u003c/p\u003e\n",
    "affective_attributes": "\u003cp\u003eWhen describing Warm and pleasantly cold (i.e., Cool) dwellings, respondents (predominantly those from Chile) mentioned attributes that seem to be more related to their aspirations and lifesteyle than to any truly Thermal factor. Specifically, elements that seem more related to how welcoming and livable a dwelling is.\u003c/p\u003e\n",
    "air_leakage": "\u003cp\u003eAir that leaks into homes (through windows, doors, and other elements)\ncan affect people’s experience in them. For instance, when\na home is kept at a pleasant temperature, hot or cold air that leaks\ninto the dwelling can dramatically change its temperature. Moreover,\nbeing directly exposed to leaking air can produce unpleasant and dramatic changes in thermal sensation.\u003c/p\u003e\n",
    "air_quality_vs_acoustic_performance": "\u003cp\u003eOpening windows allows cleaning a dwelling’s air. However, because of the existence of external noise, people sometimes need to choose between tolerating an unpleasant acoustic situation (i.e., by opening the windows) and breathing what feels like unhealthy or polluted air (i.e., by keeping the windows closed). Moreover, even if \u003ca href=\"code=ventilation_system\"\u003eventilation systems\u003c/a\u003e\ncan potentially solve this problem, they can be noisy or can transmit noise, ultimately offering a similar set of alternatives: to tolerate noise or to tolerate air that is not clean.\u003c/p\u003e\n",
    "air_temperature": "\u003cp\u003eThe temperature of the air within a space is an important\ndeterminant of thermal comfort. This has been evidenced\nby the thermal comfort literature numerous times. However, the temperature of the air also seems to influence people’s perception of air quality; specifically, low temperatures tend to be associated with a cleaner air and high ones with less clean air.\u003c/p\u003e\n\u003cp\u003eIt is possible that when people talk about “air temperature”\nthey are actually talking about Operative Temperature or Mean\nRadiant Temperature without knowing it.\u003c/p\u003e\n",
    "attractiveness_of_the_space": "\u003cp\u003eOne of the functions of daylight, according to the respondents,\nis to make spaces more attractive. They look better\nand more welcoming.\u003c/p\u003e\n",
    "availability_of_windows_and_skylights": "\u003cp\u003eWindows and skylights are probably the most common and intuitive\nway of letting daylight and air into the dwelling. However, not all windows and\nskylights are equally effective. On the contrary,\nif a room has windows or skylights that are obstructed, or too\nsmall, or there are very few of them, people might not get\nthe impression of it being properly illuminated.\u003c/p\u003e\n\u003cp\u003eAs to what do people mean by “decent size” and “lots of windows”,\nwe don’t know. It is possible for this to depend on the\n\u003ca href=\"code=views\"\u003eviews\u003c/a\u003e, the \u003ca href=\"code=site_characteristics\"\u003esite\u003c/a\u003e,\nand perhaps some other factors.\u003c/p\u003e\n",
    "awareness_of_air_pollution": "\u003cp\u003eAir pollution is not always visible and people are not always capable of perceiving it inside their homes.\nHowever, either because of the news or by looking at it from afar, people are often aware that pollution is there. This can psychologically affect their perception of air quality.\u003c/p\u003e\n",
    "bed_temperature": "\u003cp\u003eSleeping is one of the things people do at home. They want to\nsleep in a bed with an appropriate temperature. If it is cold,\nit seems to be something they do remember.\u003c/p\u003e\n\u003cp\u003eThe temperature of the bed is, obviously, related to the temperature\nof the bedroom. However, when talking about warmness, people\nspecifically mentioned the bed; whereas, when talking about coolness,\nthey talked about the temperature of the whole room. This might be\nexplained by the fact that, when it is too hot, people do not get\n\u003cem\u003ein\u003c/em\u003e the bed, necessarily.\u003c/p\u003e\n",
    "bothering_others": "\u003cp\u003eThe feeling of comfort is a state of the mind, and thus it is not\nlimited to physiological sensations or even to a person’s own\nbody. One example of this is how people worry about bothering\nothers.\u003c/p\u003e\n\u003cp\u003eFor instance, people often worry about making noise that\ncan be unpleasant for other people in the house and also of\nneighbours. Something similar might happen when cooking, in which\nthe odours of one individual’s kitchen can affect neighbours.\u003c/p\u003e\n",
    "breezes": "\u003cp\u003eLetting outside air come into the dwelling allows both reducing people’s \u003ca href=\"code=thermal_sensation\"\u003ethermal sensation\u003c/a\u003e and\ncleaning the air. An actual breeze—as opposed to just heat-driven convective currents—seems to be the feedback that people need to \u003cem\u003eperceive\u003c/em\u003e that fresh air is coming in.\u003c/p\u003e\n",
    "budget": "\u003cp\u003eWhile people do want to be comfortable, they will not necessarily\nspend all the money necessary to make their homes comfortable. On the contrary, some of them seem to have a pre-allocated budget for utility bills. When that budget is not enough, they might chose to sacrifice comfort in favour of keeping the utility bills low.\u003c/p\u003e\n\u003cp\u003eWhile a person’s socioeconomic condition will affect their budget, it\nis not necessarily true that people who can afford to do it will pay\nwhatever it takes.\u003c/p\u003e\n",
    "bugs": "\u003cp\u003eOpening windows is very useful for cooling down dwellings. However,\nif there are bugs outside, this becomes an issue. Simple solutions, such as fly-screens, might be enough to solve this issue.\u003c/p\u003e\n",
    "cleanability_of_the_space": "\u003cp\u003eAll homes will contain some dust and dirt. Nonetheless, not all of them are equally easy to clean. Materials that are easier to\nclean tend to be associated with better air quality. See also \u003ca href=\"code=dust_and_smoke\"\u003edust\u003c/a\u003e as an environmental cue.\u003c/p\u003e\n",
    "cleanliness_of_the_space": "\u003cp\u003ePeople care about how clean the spaces they use are. This perception of cleanliness seems to be influenced by how well illuminanted the space is, by the perceived quality of its air, and by its temperature. Hot, humid, and dark places are perceived as unhygienic.\u003c/p\u003e\n",
    "colour_of_the_space": "\u003cp\u003eDaylight will penetrate more or less into the space depending on\nthe colour (or, more specifically, the reflectivity) of the materials\nin the space. Lighter colours would allow daylight to get further into\nrooms, which was raised by some respondents.\u003c/p\u003e\n\u003cp\u003eAlso, dark colours seem to be associated with cold and unhygienic spaces.\u003c/p\u003e\n",
    "complete_silence_vs_sounds_of_nature": "\u003cp\u003ePeople do not necessarily want absolute silence but for the soothing sound of nature (see \u003ca href=\"code=the_sound_of_silence\"\u003eThe Sound of Silence\u003c/a\u003e). However, sometimes they need to\nchoose between blocking both the pleasant natural sounds as well as human noises, or letting both in. It would seem that people generally prefer to block it all.\u003c/p\u003e\n",
    "condensation_and_mould": "\u003cp\u003ePerceivable condensation and mould are indicators of cold and humidity, thus related to a lack of air quality and warmness.\u003c/p\u003e\n",
    "coolness_vs_warmness": "\u003cp\u003eThis model treats coolness and warmness separately, but they are tightly related. People\nknow that favouring one over the other might not be beneficial in the end. Balance is needed.\u003c/p\u003e\n",
    "damage_to_objects_in_the_house": "\u003cp\u003ePeople like spaces with plenty of natural light. However, they know that solar radiation can damage objects in the dwelling.\u003c/p\u003e\n",
    "daylight_sufficiency": "\u003cp\u003eA space will be perceived as “sufficiently illuminated” when it has just\nenough natural light for the sun to warm it up and operating without\nthe need for electric lighting. However, this quantity does not\nseem to be nearly enough. People mentioned the need for\n\u003cem\u003equality\u003c/em\u003e of light instead of \u003cem\u003equantity\u003c/em\u003e of it and also that they\nwant much more light than what is required to read a book.\u003c/p\u003e\n\u003cp\u003eHaving enough daylight also seems to be a requisite for a dwelling to be described as Cool, and can make spaces feel cleaner thus favouring their Air Quality.\u003c/p\u003e\n",
    "daylight_vs_thermal_comfort": "\u003cp\u003eIncreasing windows to maximize daylight has the consequence\nof reducing thermal insulation and thus increasing the chances\nof feeling cold.\u003c/p\u003e\n\u003cp\u003eAlso, maximizing daylight and warmth can lead to\nan excessively hot home in summer, if not done carefully. People need\nto choose, then, between having plenty of daylight while suffering\nfrom high temperatures and being thermally comfortable in a\nrelatively dark home.\u003c/p\u003e\n",
    "direct_vs_diffuse_light": "\u003cp\u003eDaylight can be separated into two components: diffuse and direct.\u003c/p\u003e\n\u003cp\u003eExamples of Diffuse Daylight are the light coming from the\nsky on a cloudy day and the light reflected by buildings\nor snow. This component of natural light creates gentle shadows\nand will often be less powerful than its direct component.\u003c/p\u003e\n\u003cp\u003eThe most obvious example of Direct Daylight is\nthe light that the sun casts on a clear sunny day. It is a\npowerful stream of light that creates strong and well-defined\nshadows.\u003c/p\u003e\n\u003cp\u003eDepending on the situation, people might prefer one over the other.\nDirect daylight carries with it a lot of heat, and thus it might\nbe unpleasant for people who live in hot and sunny locations.\u003c/p\u003e\n",
    "direction_of_the_light": "\u003cp\u003eWhile it is not entirely clear why this happens, the angle of the natural\nlight entering the space might matter. Specifically, respondents\nfrom Santiago (Chile) argued that the more vertical the\nangle of natural light, the better. Two reasons for this were given.\nThe first one is that vertical sun is easier to control\n(i.e. it does not strike over the whole room, just the perimeter),\nwhich is convenient for hot locations with strong solar radiation. The\nsecond reason was related to the fact that light coming from\nabove emulates an exterior light setting\nbetter than lateral light.\u003c/p\u003e\n",
    "doors_between_spaces": "\u003cp\u003ePreventing noise and transmission of odours is not always easy. However, sometimes,\nhaving some doors that separate the different spaces in the dwelling is enough. This \u003ca href=\"code=effective_and_simple_systems\"\u003emechanism\u003c/a\u003e\nseems to be a good indicator of \u003ca href=\"layer=expected_outcomes\"\u003ehow noisy the dwelling might become in the future\u003c/a\u003e.\u003c/p\u003e\n",
    "dust_and_smoke": "\u003cp\u003eWhile not always included in the list of relevant factors related to air quality,\ndust can be quite annoying for people. Different \u003ca href=\"code=site_characteristics\"\u003esites\u003c/a\u003e and [neighbourhoods] (code=neighbourhood_characteristics) will be\nmore or less exposed to dust.\u003c/p\u003e\n\u003cp\u003eSmoke, of course, has a similar effect. However, it can be less dependant on the site and the neighbourhood and more on neighbours.\u003c/p\u003e\n\u003cp\u003eSee also the \u003ca href=\"code=cleanability_of_the_space\"\u003ecleanability of the space\u003c/a\u003e.\u003c/p\u003e\n",
    "dwelling_typology": "\u003cp\u003eDepending on whether people are looking for, or live in,\nan apartment, detached or attached house, or a different\nkind of dwelling, their experiences and concerns will\nvary. This is particularly important for the long-term inferences people make when searching for a new home to live in.\u003c/p\u003e\n",
    "effective_and_simple_systems": "\u003cp\u003eDwellings have systems that aim to make them more comfortable, such as heaters, mechanical ventilation, and electric lighting. In order to be utilized, these systems should act quickly and be simple to use.If the systems in a dwelling are ineffective at solving problems, people can feel helpless.\u003c/p\u003e\n",
    "energy_efficiency": "\u003cp\u003eHeating, cooling, lighting and ventilating\nall consume energy. Some people expressed their concern with regards\nto the environmental impact of their actions. People will need\nto choose whether they want to be comfortable while producing some\nnegative environmental impacts; or feeling relatively uncomfortable\nwhile lowering the environmental impacts of their actions.\u003c/p\u003e\n\u003cp\u003eWhile strongly related to the Trade-Off of \u003ca href=\"code=utility_bills\"\u003eUtility Bills\u003c/a\u003e, the\nmotivation of favouring energy efficiency does not necessarily rely\non financial estimations.\u003c/p\u003e\n",
    "exposure_to_solar_radiation": "\u003cp\u003eEven when the air in a room is maintained at a subjectively pleasant  temperature, being exposed\nto solar radiation can significantly affect people’s thermal\nperception and thermal comfort. If it is cold, the sun might be\nwelcomed; but if it is hot, it is definitely not.\u003c/p\u003e\n\u003cp\u003eAlso, rooms that are exposed to solar radiation are associated to a lack of humidity and dampness.\u003c/p\u003e\n",
    "exposure_to_wind": "\u003cp\u003eIn some places, wind can be strong enough to become an impediment to open windows. This can prevent people from ventilating their homes and, in consequence, from enjoying clean air.\u003c/p\u003e\n",
    "feeling_of_confinement": "\u003cp\u003eSome people reported that naturally illuminated spaces\nfeel less enclosed. It is possible that this perception is related to the perception of\n\u003ca href=\"code=sense_of_connection_with_the_exterior\"\u003eSense of Connection with the Exterior\u003c/a\u003e,\nalthough further research is needed to verify this. Similarly,\nit is hard to know whether this effect would still exist\nif daylight was provided without views.\u003c/p\u003e\n\u003cp\u003eThe Feeling of Confinement is also perceived in spaces that are excessively hot or in which the air feels heavy and stuffy. As mentioned in the code of \u003ca href=\"code=air_temperature\"\u003eAir Temperature\u003c/a\u003e, these two variables—the perceived quality of the air and the air temperature—seem to be related.\u003c/p\u003e\n",
    "floor_contact_temperature": "\u003cp\u003eThe floor contact temperature seems to be an important\ndeterminant of the perception of thermal comfort in dwellings.\nThis is affected by both the temperature of the floor top surface\n(as measured through a thermometer) and the thermal properties\nof the materials in the floor. Specifically, the material’s\n\u003ca href=\"https://en.wikipedia.org/wiki/Thermal_effusivity\"\u003eThermal Effusivity\u003c/a\u003e.\u003c/p\u003e\n",
    "floor_number": "\u003cp\u003eUpper storeys or floors seem to be associated with more heat. Sometimes the explanation is\nthat heat goes up (e.g., the upper floors in a house are hotter than the lower ones), and also that apartments that are higher take\nadvantage of the heat of apartments below.\u003c/p\u003e\n\u003cp\u003eSome other explanations were identified (e.g., there are no windows or cooling) but, generally, it seems that upper storeys are warmer/hotter than others.\u003c/p\u003e\n",
    "freedom_to_do_what_you_want_wherever_you_want": "\u003cp\u003eA comfortable home should allow people to carry on with their\nlives without being an impediment. People seem to want a home\nthat will not significantly affect their lifestyles.\u003c/p\u003e\n",
    "glare": "\u003cp\u003eGlare is the difficulty for seeing, strongly associated to\nexcessive contrast or brightness. While quite important in\noffice settings, it seems to be relatively irrelevant in\nresidential settings.\u003c/p\u003e\n",
    "heating_and_cooling_system": "\u003cp\u003eIn areas that are too cold or hot, having a mechanical heating and/or cooling system might be the only option for ensuring that the space can be maintained at a pleasant\ntemperature.\u003c/p\u003e\n",
    "household_composition": "\u003cp\u003eThe feeling of comfort is a state of the mind, and thus\nit is not limited to physiological sensations or even\nto individuals’ own body. The health and wellbeing of\nothers, such as children and family, can deeply affect\na person’s satisfaction with a home, thus affecting\ntheir \u003ca href=\"code=mental_wellbeing\"\u003eMental Wellbeing\u003c/a\u003e.\u003c/p\u003e\n",
    "increased_maintenance_and_reduced_durability": "\u003cp\u003eSome technologies and construction materials are\nbeneficial for comfort. However, they sometimes\ncarry with them an extra costs or they do not last as much\nas other alternatives.\u003c/p\u003e\n",
    "lifestyle": "\u003cp\u003eAn important component of the \u003ca href=\"layer=comfort\"\u003efeeling of comfort\u003c/a\u003e\nis the \u003ca href=\"code=freedom_to_do_what_you_want_wherever_you_want\"\u003efreedom to do what you want wherever you want\u003c/a\u003e.\nIn other words, people want homes that do not prevent them from living according to their desired lifestyle.\u003c/p\u003e\n",
    "light_pollution": "\u003cp\u003eOpening curtains and windows at night can become an issue when\nthere is too much light outside. This can prevent people from cooling down their homes by ventilating them during the night.\u003c/p\u003e\n",
    "location": "\u003cp\u003eLocation is one of the first factors that people\nconsider when searching for a new home. Commuting is, generally,\nnot fun at all. However, while making this choice,\npeople need to decide between enjoying the benefits of a centrally\nlocated home or the quietness and peace of the more remote suburbs.\u003c/p\u003e\n\u003cp\u003eOf course, the \u003ca href=\"code=streets_nearby\"\u003estreets nearby\u003c/a\u003e will also\ninfluence this trade-off. For instance, there might be some centrally\nlocated homes that have a good acoustic performance due to the specific street they are located in. But this is\nnot necessarily the case for all homes.\u003c/p\u003e\n",
    "loss_of_views": "\u003cp\u003eViews are not always in the direction that maximizes\ndaylight, minimizes noise, and ensures coolness. Thus, people sometimes need to choose between enjoying Views and living in a Cool dwelling with a good Acoustic Performance and Daylight.\u003c/p\u003e\n",
    "loss_of_visual_privacy": "\u003cp\u003eIncreasing the transparency in the facade increases the amount\nof natural light, but it also reduces visual privacy. Similarly, choosing the right orientation and opening windows often allows preventing overheating in the dwelling. However, these two actions will sometimes lead to facing other apartments and/or to being visible from the outside.\u003c/p\u003e\n",
    "loudness_vs_origin": "\u003cp\u003e\u003ca href=\"https://en.wikipedia.org/wiki/Loudness\"\u003eLoudness\u003c/a\u003e\nis a measure of how strong a sound is, and depends mostly\non pressure level (i.e. decibels) and frequency. However, it is important to acknowledge that\nnoises (i.e., unwanted sounds) of equal loudness may be more or less unpleasant at different times of the day or in different situations and depending on their source.\u003c/p\u003e\n\u003cp\u003ePeople distinguish clearly between different sources\nof noise.\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003e\n\u003cp\u003eNoise from neighbours\u003c/p\u003e\n\u003c/li\u003e\n\u003cli\u003e\n\u003cp\u003eNoise from common spaces (e.g. pools, parks, lobbies)\u003c/p\u003e\n\u003c/li\u003e\n\u003cli\u003e\n\u003cp\u003eCity noise (e.g. traffic, horns, etc.)\u003c/p\u003e\n\u003c/li\u003e\n\u003cli\u003e\n\u003cp\u003eToilet and pipes noise\u003c/p\u003e\n\u003c/li\u003e\n\u003cli\u003e\n\u003cp\u003eNoises that come from the house itself (e.g. squeaky doors, cracking floors)\u003c/p\u003e\n\u003c/li\u003e\n\u003cli\u003e\n\u003cp\u003eNoises produced by those who live in the house (e.g. kitchen appliances, children, pets)\u003c/p\u003e\n\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eThese different sources will trigger different cognitive\nresponses. For instance, noises from neighbours, common spaces,\nand those from the city cannot be controlled and are not part of the natural consequence of their actions, thus being highly\nunpleasant. On the contrary, the noise produced by those who\nlive in the house is relatively easier to control and therefore\nless unpleasant. This is highly related to the\n\u003ca href=\"layer=expected_outcomes\"\u003eexpected outcomes\u003c/a\u003e.\u003c/p\u003e\n\u003cp\u003eToilet and pipes noises, on their part, are likely to contribute\nto a perception of reduced \u003ca href=\"code=acoustic_privacy\"\u003eacoustic privacy\u003c/a\u003e. Finally, noises that come from the house itself are interpreted as an\nindicator of wear and tear, and therefore are unpleasant.\u003c/p\u003e\n",
    "love_for_music": "\u003cp\u003ePeople who like listening to or playing music may be\nparticularly sensitive to acoustic conditions. They might worry about\n\u003ca href=\"code=bothering_others\"\u003ebothering others\u003c/a\u003e with their music, meaning that the dwelling is stopping them from\n\u003ca href=\"code=freedom_to_do_what_you_want_wherever_you_want\"\u003efreely choosing their lifestyle\u003c/a\u003e.\u003c/p\u003e\n",
    "materials_perceived_as_humid": "\u003cp\u003eThere seem to be some construction materials that, according to people, absorb water and\nthus tend to be more or less beneficial to air quality. Nonetheless, only a few people\nmentioned this and they do not agree with\neach other.\u003c/p\u003e\n",
    "materials_that_feel_warm": "\u003cp\u003ePeople seem to perceive some materials as being warmer than others.  This might be related to the\n\u003ca href=\"https://en.wikipedia.org/wiki/Thermal_effusivity\"\u003ethermal effusivity\u003c/a\u003e—mentioned also when discussing the\n\u003ca href=\"code=floor_contact_temperature\"\u003eFloor contact temperature\u003c/a\u003e—\nbut also to more aesthetic reasons. Further research is\nrequired.\u003c/p\u003e\n",
    "mean_radiant_temperature": "\u003cp\u003eSometimes it is not the air that is hot or the sun that is striking but heat irradiated\nfrom certain hot surfaces. It feels different.\u003c/p\u003e\n",
    "mental_wellbeing": "\u003cp\u003eA comfortable home makes people happy and fills them with\nenergy. It allows them to be sure that their families will\nbe healthy.\u003c/p\u003e\n",
    "neighbourhood_characteristics": "\u003cp\u003eThe infrastructure and the nature of the constructions in different\nneighbourhoods affect the way these are perceived by people. Some\nneighbourhoods, for example, have a great number of restaurants, others\nare close to land fields, others only have offices and thus are nearly\nempty at night.\u003c/p\u003e\n\u003cp\u003eSimilarly, institutional differences can also affect the way in which\nneighbourhoods perform. For instance, some neighbourhoods allow people to use\nlog burners and/or pubs to stay open till late while others do not. This affects\nthe quality of life of the people who live in it.\u003c/p\u003e\n\u003cp\u003eThis code, together with \u003ca href=\"code=neighbourhood_demographics\"\u003eneighbourhood demographics\u003c/a\u003e,\ndescribe the location at a neighbourhood scale. Specifically, while \u003ca href=\"code=neighbourhood_demographics\"\u003eDemographics\u003c/a\u003e\ndescribes the human factors (e.g., people are quiet, old, young, etc.),  this code describes the more physical factors.\nAlso, the \u003ca href=\"code=site_characteristics\"\u003eSite characteristics\u003c/a\u003e describe the location at a smaller scale.\u003c/p\u003e\n",
    "neighbourhood_demographics": "\u003cp\u003eNot everyone likes to do the same things at the same time. These differences\ncan be, at least in part, explained by the demographics of different groups.\nFor instance, young people tend to stay until late while older people or families tend to\nget up early. This affects the experience of people in certain neighbourhoods.\u003c/p\u003e\n\u003cp\u003eThis code, together with \u003ca href=\"code=neighbourhood_characteristics\"\u003eneighbourhood characteristics\u003c/a\u003e,\ndescribe the location at a neighbourhood scale. Specifically, while Demographics describe\nthe human factors, the \u003ca href=\"code=neighbourhood_characteristics\"\u003echaracteristics\u003c/a\u003e describe\nthe more physical factors (e.g., neighbouring infrastructure, restaurants, etc.)\u003c/p\u003e\n",
    "nuisances_and_lack_of_safety": "\u003cp\u003eJust as in the case of \u003ca href=\"code=utility_bills\"\u003eutility bills\u003c/a\u003e, safety\ncan be a priority for people. Thus, all appliances and systems in their\nhomes should be safe to operate so people are not forced to choose\nbetween their safety and their comfort. Also, operating these\nsystems should not be unpleasant enough for them to be left unused.\u003c/p\u003e\n",
    "odours": "\u003cp\u003eThe sense of smell is used to assess air quality. Bad smells are associated with poor air quality.\u003c/p\u003e\n",
    "openness_of_the_space": "\u003cp\u003eHaving more \u003ca href=\"code=doors_between_spaces\"\u003edoors between spaces\u003c/a\u003e reduces the\ntransmission of noise and odours across the space. However, some people would rather not\nhave these doors due to their lifestyle and preferences. This is a choice they have to make.\u003c/p\u003e\n",
    "orientation": "\u003cp\u003eThe sun does not strike equally in all directions. In the northern\nhemisphere, the sun will generally strike from the South; while in\nthe southern hemisphere, from the North. These differences imply that\nsome orientations will receive more sunlight and, therefore, be hotter,\nbrighter and more or less pleasant.\u003c/p\u003e\n",
    "passive_design": "\u003cp\u003eHaving heating, lighting, cooling, and ventilation systems that\nare simple to use, effective, cheap to run, and reliable is a good thing. However,\nhaving a home that does not often rely on these systems is even better.\u003c/p\u003e\n",
    "pets": "\u003cp\u003ePets—specifically the \u003ca href=\"code=proximity_to_neighbours\"\u003eneighbours’\u003c/a\u003e pets—can be the source\nof noise, allergies, and other nuisances.\u003c/p\u003e\n",
    "physical_wellbeing": "\u003cp\u003eComfortable homes favour people’s health.\u003c/p\u003e\n\u003cp\u003eThis manifestation of comfort seems to be less important in the domain of Acoustics. The\nreason for this is probably that, generally, the range of noises and sounds to which\npeople are exposed to in their everyday life is not loud enough to cause physiological\ndamage.\u003c/p\u003e\n",
    "protection_from_moisture": "\u003cp\u003eHumid locations can feel cold on the outside and thus people\nworry that the homes in those locations being cold. Barriers and\nmechanisms can help.\u003c/p\u003e\n",
    "proximity_to_neighbours": "\u003cp\u003eNeighbours can be the source of certain nuisances that are particularly hard to control.\nSpecifically, noise, privacy, and odours seem to be common concerns. This might be related to their \u003ca href=\"code=pets\"\u003epets\u003c/a\u003e\nor to the neighbours themselves.\u003c/p\u003e\n\u003cp\u003eSo, if neighbours are too close, people will infer that they\nwill be exposed to some uncomfortable situations in the future.\u003c/p\u003e\n",
    "relative_humidity": "\u003cp\u003eA high (perceived) relative humidity seems to be associated with poor air quality and a higher \u003ca href=\"code=thermal_sensation\"\u003ethermal sensation\u003c/a\u003e.\u003c/p\u003e\n",
    "safety": "\u003cp\u003ePeople often want to open the windows for ventilating or cooling their homes. However,\nleaving the windows open is not always a good idea due to safety concerns (e.g., people can\ncome in through the windows or people can fall out of them).\u003c/p\u003e\n\u003cp\u003eSimilarly, while it is common ti like quiet homes, a dwelling that is excessively quiet can\nmake people feel disconnected from the other members of their household and, in consequence,\nmake them feel unsafe.\u003c/p\u003e\n",
    "sensation_when_entering_a_space": "\u003cp\u003eFirst impressions count. Even if they are brief, it is possible\nthat the short experience of entering a comfortable space leaves\nsome mark in people’s overall assessment of such a space’s comfort.\u003c/p\u003e\n\u003cp\u003eThis might, or might not (depending on the domain), be related to\nthe physiological phenomenon known as\n\u003ca href=\"https://en.wikipedia.org/wiki/Alliesthesia\"\u003eAlliesthesia\u003c/a\u003e. This\nis the pleasure felt when a certain external stimuli restores\nsome internal variable that was misplaced. For instance, people often\nfeel this when entering a warm space after walking in\nthe cold for a relatively ling time, and when being exposed to a cool breeze when feeling\ntoo hot.\u003c/p\u003e\n",
    "sense_of_community": "\u003cp\u003eEven if \u003ca href=\"code=proximity_to_neighbours\"\u003eneighbours might be the source of some nuisances\u003c/a\u003e, people\nseem keen to be part of a community. This perception seems to be particularly (although not\nexclusively) produced by the sound that other people make when performing recreational\nactivities, such as playing, laughing, and practising sports.\u003c/p\u003e\n",
    "sense_of_connection_with_the_exterior": "\u003cp\u003eHaving daylight allows people to connect with the exterior.\nIt helps them feel how the time passes and to distinguish between daytime\nand night time.\u003c/p\u003e\n\u003cp\u003eIt is possible that this perception is related to the\nreduced \u003ca href=\"code=feeling_of_confinement\"\u003efeeling of confinement\u003c/a\u003e—also influenced by Daylight—,\nbut confirming this requires further research.\u003c/p\u003e\n",
    "sensitivity_to_noise": "\u003cp\u003eSome people are simply more sensitive to noise than others.\nWhether this is because of some illness, the\nnature of their job, or simply because of personal preferences,\nunderstanding the specific requirements can be significantly\nrelevant.\u003c/p\u003e\n",
    "sensitivity_to_odours_and_dust": "\u003cp\u003eSome people are more sensitive to odours and dust than others. Reasons for\nthis include a good/bad sense of smell, allergies,\nor simply caring more or less about it.\u003c/p\u003e\n",
    "site_characteristics": "\u003cp\u003eNot all sites in the same neighbourhood are the same. Obstructions—such as retaining walls, trees,\nor hills—can make a site less sunny while protecting it from the wind. Similarly, green\nareas are seen as beneficial for air quality and for preventing overheating. These cues can\nbe read by people to infer what the future might be like.\u003c/p\u003e\n\u003cp\u003eThis code is similar to the \u003ca href=\"code=neighbourhood_characteristics\"\u003eneighbourhood characteristics\u003c/a\u003e\nbut at a smaller scale (i.e. site scale as opposed to urban scale).\u003c/p\u003e\n",
    "size_of_the_space": "\u003cp\u003eThe size of the space affects our perception of it and also its\nthermodynamic and optical behaviour. Bigger spaces tend to be\nharder to warm up and cool down, and smaller spaces are associated with a Feeling\nof Confinement (which is related to Coolness). This characteristic\nis one of the first elements that people notice, sometimes influencing their assessment of comfort.\u003c/p\u003e\n",
    "streets_nearby": "\u003cp\u003eStreets have cars, buses and trucks. These are noisy, dirty and smelly.\u003c/p\u003e\n\u003cp\u003eNot all streets are the same, though. People tend to know\nwhich streets are busier and which streets are quiet.\u003c/p\u003e\n",
    "systems_that_do_not_fail": "\u003cp\u003eHopefully, homes should be robust enough to\nconsistently offer comfortable spaces for people. This implies,\nfor instance, that heaters should fail as little as possible; and\nif they fail, this event should not prevent the whole house\nfrom being liveable. In a similar manner, windows, doors, roofs,\nand other architectural elements of the dwelling should perform\nappropriately in a consistent manner.\u003c/p\u003e\n",
    "temporary": "\u003cp\u003eNuisances and uncomfortable situations can always happen. When there seem to be no\n\u003ca href=\"code=effective_and_simple_systems\"\u003emeans to solve them\u003c/a\u003e, the best people can do is to expect they finish soon. \u003cem\u003eKnowing\u003c/em\u003e that something will—or will not—end soon modulates people’s feeling\nof Comfort.\u003c/p\u003e\n",
    "the_sound_of_silence": "\u003cp\u003eWhile, at first, people tend to say that absolute silence is what they want, it seems that they enjoy hearing \u003cem\u003esome\u003c/em\u003e sounds. Consequently, the sound of silence is not \u003cem\u003eabsolute\u003c/em\u003e silence, but actually soothing—mostly natural—sounds.\u003c/p\u003e\n",
    "thermal_comfort_vs_acoustic_performance": "\u003cp\u003ePeople commonly open the windows when it is hot. However,\nsometimes this results in an even more unpleasant situation\ndue to exterior noise.\u003c/p\u003e\n",
    "thermal_comfort_vs_air_quality": "\u003cp\u003eVentilating implies bringing fresh air into the home. Doing this during\ncold days can be a nuisance, as that air will be cold and might lower the\ntemperature of the whole house. Something similar happens during hot days.\nThe choices are to ventilate and feel thermally uncomfortable, or not to\nventilate and feel relatively fine. (This is, of course, assuming that it\nis possible to maintain the dwelling at a more pleasant temperature than\nthe exterior)\u003c/p\u003e\n",
    "thermal_insulation": "\u003cp\u003eWhether they have been taught about this or they intuitively\nknow it, thermal insulation is one of the characteristics\nthat people use when making predictions about thermal\ncomfort. Also, thermal insulation seems to be associated with dry dwellings;\nthat is, dwellings that are not damp and mouldy.\u003c/p\u003e\n",
    "thermal_mass": "\u003cp\u003eWhile probably related to (and, perhaps, even confused with) \u003ca href=\"code=thermal_insulation\"\u003ethermal insulation\u003c/a\u003e, thick and heavy\nwalls are noticed by people. These appear to be associated with homes that overheat\nless often.\u003c/p\u003e\n",
    "thermal_preference": "\u003cp\u003eWhile people tend to agree about the range of temperatures\nthat are considered acceptable (i.e., somewhere around\n18C to 26C), choosing an exact temperature within this\nrange is complicated. Thermal preferences vary within this\nrelatively small range of temperatures.\u003c/p\u003e\n",
    "thermal_sensation": "\u003cp\u003eThermal sensation is the name that has been historically\ngiven to the perception of how cold or hot is the space.\nIt is usually measured using bipolar adjective (i.e., a\nLikert) scale that goes from “Too Cold” to “Too Hot”\ngoing through “Neutral”.\u003c/p\u003e\n\u003cp\u003eIt is very often assumed that “neutral” or “nearly-neutral”\nthermal sensations imply comfort. So, people’s quotes gathered\nwithin this code include those referring to pure perception (e.g.,\n“cold”, “hot”) and also to thermal preference (e.g., “pleasant\ntemperature”).\u003c/p\u003e\n\u003cp\u003eSince Thermal Sensation is a perception that considers\nthe overall thermal environment, it might be necessary\nto consider that different parts of people’s body might\nfeel colder or hotter. This is reflected, for instance,\nin that the \u003ca href=\"code=floor_contact_temperature\"\u003efloor contact temperature\u003c/a\u003e\nseems to be quite relevant for people.\u003c/p\u003e\n",
    "times_of_occupancy": "\u003cp\u003eThe experience of people in a certain dwelling might be\ndramatically different depending on their routines and\nschedules. A retired person, for instance, might want\nto have daylight all day. Whereas a busy person who gets\nhome late and only sleeps there might favour mornings or\nevenings.\u003c/p\u003e\n",
    "uncomfortable_amount_of_clothing": "\u003cp\u003eWhile people can feel warmer by wearing more layers of clothing,\nthey do not always do it happily. Sometimes people feel that they\nneed to wear more layers than what they find appropriate. The same happens\nduring hot days, when people can potentially take off more layers but they\nhesitate. The options are, then, to wear comfortable clothing while feeling relatively uncomfortable, or to wear more appropriate clothing while feeling more comfortable.\u003c/p\u003e\n",
    "utility_bills": "\u003cp\u003eUtility bills that are too expensive can prevent people from heating and\ncooling, thus negatively affecting their living experience. Some people will\nspend whatever amount of money is required to be comfortable, but others will\nsimply sacrifice their level of comfort\nand avoid spending more than what they have budgeted to this\nfield.\u003c/p\u003e\n\u003cp\u003eThis is related to people’s \u003ca href=\"code=budget\"\u003ebudget\u003c/a\u003e.\u003c/p\u003e\n",
    "ventilation_system": "\u003cp\u003e\u003ca href=\"code=availability_of_windows_and_skylights\"\u003eWindows\u003c/a\u003e are good for air quality. But\nthey are not always available or sometimes they are not effective enough. A mechanical\nventilation system—e.g. an exhaust fan—can help.\u003c/p\u003e\n\u003cp\u003eIt is worth noticing that some people do not trust these systems too much, which is\nwhy they favour opening windows.\u003c/p\u003e\n",
    "views": "\u003cp\u003eThe \u003ca href=\"code=availability_of_windows_and_skylights\"\u003eavailability of windows and skylights\u003c/a\u003e\nnot only provides daylight but also views. This was identified\nby some respondents, who argued that dwellings with good daylight also\nhave views.\u003c/p\u003e\n\u003cp\u003eThere is a self-evident correlation between views and daylight.\nHowever, it is unclear whether different views to outside (more open,\nobstructed, rural or urban) will affect the perception of\nbrightness of the space, or the satisfaction with it in terms\nof visual comfort.\u003c/p\u003e\n",
    "weather_sounds": "\u003cp\u003eThe amount of noise or sound from the exterior—e.g. rain, hail, wind—seems\nto influence people’s Feeling of Comfort. This appears to be related to\n\u003ca href=\"layer=expected_outcomes\"\u003eexpected outcomes\u003c/a\u003e; specifically, to\n\u003ca href=\"code=systems_that_do_not_fail\"\u003ethe fear of the envelope failing\u003c/a\u003e to protect\nthem from the external elements.\u003c/p\u003e\n"
}